version: '3.3'

services:

  s_nginx:
    container_name: s_nginx
    build:
        context: ./docker.config/nginx
#    image: nginx
    volumes:
      - ./docker.config/nginx/nginx.conf:/etc/nginx/conf.d/defaulf.conf
      - ./docker.config/nginx/access.log:/var/log/access.log
      - ./docker.config/nginx/error.log:/var/log/error.log
      - ./public/:${APP_PATH_CONTAINER}public/
    working_dir: ${APP_PATH_CONTAINER}
    ports:
      - 8183:80
    links:
      - fpm

  fpm:
    container_name: fpm
    build:
      context: ./docker.config/fpm
#      context: ./docker.config/lorisleiva
    volumes:
      - ./:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
#    command:
#      - source ~/.profile
#      - nvm install node
#      - nvm install 8.10.0
    links:
      - mysql_5_7



  mysql_5_7:
    container_name: mysql_5_7
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${CONTAINER_DEFAULT_DB_ROOT_PASS}'
      MYSQL_DATABASE: laravel
      TZ: Europe/Kiev
    ports:
      - 33061:${CONTAINER_MYSQL_DEFAULT_PORT}
    volumes:
      - ./mysql5_7:${DB_PATH_CONTAINER}:rw

  s_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOSTS=${APP_LOCAL_HOST}:33061
      - PMA_VERBOSES=mysql_5_7(${APP_LOCAL_HOST}:33061))
    restart: always
    ports:
      - ${CONTAINER_PHP_NY_ADMIN_PORT}:${CONTAINER_APACHE_DEFAULT_PORT}
    volumes:
      - /sessions

  s_composer:
    container_name: s_composer
    build:
      context: ./docker.config/composer
#    image: composer:1.8.5
    volumes:
      - ./:${APP_PATH_CONTAINER}
#    working_dir: ${APP_PATH_CONTAINER}
#    links:
#      - fpm
#    command: composer install

volumes:
  mysql5_7:
  sessions:
